name: cyguardian
description: A sleek, enterprise-grade cyber risk assessment application.

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  fl_chart: ^0.63.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/icons/Saudi_Riyal_Symbol.svg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/logo.png
  #   - images/background.jpg

  # To add custom fonts to your application, add a fonts section, like this:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
